//
// Created by ydar on 2021/1/26.
//

#ifndef YD2D_INCLUDE_YD2D_PLATFORMS_BASE_PLATFORM_HPP_
#define YD2D_INCLUDE_YD2D_PLATFORMS_BASE_PLATFORM_HPP_





#endif //YD2D_INCLUDE_YD2D_PLATFORMS_BASE_PLATFORM_HPP_
